### ISSUE TITLE
"The sepcified environments are created, if an environment exists it is first removed."

### ISSUE THREAD

**Issue by mikehsndba** [xebialabs-community/xld-ssis-plugin#1]
XL folks recommended I ask you a question, hope it's not a stupid one.

I have a single environment supporting many projects.  I could deploy 100 different projects, all using portions of same environment.  This statement in the readme.md seems alarming, seems analogous to deploying a table change to a DB, and if the DB already exists it is first removed.  

Am I just misinterpreting the readme?

I'm not experienced with ISPAC?  I've tried to read up on this and so far doesn't seem like they force this wholesale replacement of the environment.  FIWW, I have deployed 100s of SSIS pkgs manually, always using VS.

**Comment by jdewinne** [comment]
According to the [synthetic.xml](https://github.com/xebialabs-community/xld-ssis-plugin/blob/master/src/main/resources/synthetic.xml#L17), the modify operation is the same as the create operation.
However, the corresponding [powershell script](https://github.com/xebialabs-community/xld-ssis-plugin/blob/master/src/main/resources/ssis/deploy-ispackage.ps1#L13) first indeed checks if the package is there, and removes the old version if present. If this is not what you want, you could of course change the script, or add a property on the deployed that makes this configurable.

**Comment by mikehsndba** [comment]
Thank you.  I'll have to learn more about synthetic.xml.

**Comment by jdewinne** [comment]
ok. I'll close the issue for now. Feel free to report any issues when needed.
